CREATE TABLE customer (
	id UUID PRIMARY KEY DEFAULT uuidv7(),
    phone VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);