CREATE TABLE note (
	id INT PRIMARY KEY IDENTITY(1,1),
    note NVARCHAR(MAX) NOT NULL,
	isDelete BIT NOT NULL DEFAULT 0,
	chatRoomId INT NOT NULL,
    updateTime DATETIMEOFFSET(7) NOT NULL,
    createTime DATETIMEOFFSET(7) NOT NULL,

	CONSTRAINT FK_note_ChatRoom FOREIGN KEY (chatRoomId) REFERENCES chatRoom(id),
);
GO
CREATE NONCLUSTERED INDEX idx_chatRoom_id ON note(chatRoomId);
GO