services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - "80:80"
      - "443:443"
    networks:
      - network_zalo_5kaquarium
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

networks:
  network_zalo_5kaquarium:
    external: true
