CREATE TABLE [order] (
    id INT PRIMARY KEY IDENTITY(1,1),
    uuid NVARCHAR(255) NOT NULL UNIQUE,
	label NVARCHAR(255) NOT NULL,
	content NVARCHAR(MAX) NOT NULL,
	money DECIMAL(20,2) NOT NULL,
	isPay BIT NOT NULL,
	phone NVARCHAR(255) NOT NULL,
    isDelete BIT NOT NULL DEFAULT 0,
	chatRoomId INT NOT NULL,  
    updateTime DATETIMEOFFSET(7) NOT NULL,
    createTime DATETIMEOFFSET(7) NOT NULL,

	CONSTRAINT FK_order_ChatRoom FOREIGN KEY (chatRoomId) REFERENCES chatRoom(id)
);
GO
CREATE NONCLUSTERED INDEX idx_chatRoom_id ON [order](chatRoomId);
GO
CREATE NONCLUSTERED INDEX idx_phone ON [order](phone);
GO

CREATE TABLE orderStatus (
    id INT PRIMARY KEY IDENTITY(1,1),
	type NVARCHAR(255) NOT NULL,
	content NVARCHAR(255) NOT NULL,
    orderId INT NOT NULL, 
    createTime DATETIMEOFFSET(7) NOT NULL,

    CONSTRAINT FK_orderStatus_Account FOREIGN KEY (orderId) REFERENCES [order](id)
);
GO
CREATE NONCLUSTERED INDEX idx_order_id ON orderStatus(orderId);
GO