CREATE TABLE customer (
	id INT PRIMARY KEY IDENTITY(1,1),
    phone NVARCHAR(255) NOT NULL UNIQUE,
    password NVARCHAR(255) NOT NULL,
    createTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
);
GO
