CREATE PROCEDURE CreateStatistics
	@fromDate DATETIMEOFFSET(7) = NULL,
    @toDate DATETIMEOFFSET(7) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
	BEGIN TRANSACTION;

		SELECT *
		FROM [statistics]
		WHERE ofDay >= CAST(@fromDate AS DATETIMEOFFSET)
		  AND ofDay < DATEADD(DAY, 1, CAST(@toDate AS DATETIMEOFFSET))
		ORDER BY ofDay;

	COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		THROW;
	END CATCH
END